---
description: "Processes user todo items"
processors:
  - rename:
      field: "userId"
      target_field: "user_id"
      ignore_missing: true
  - rename:
      field: "id"
      target_field: "task_id"
      ignore_missing: true
  - remove:
      field: "completed"
      ignore_missing: true